--CREATE DATABASE DISTRIBUIDORA_ESB
CREATE TABLE VEHICULO(

  Placa VARCHAR(8) PRIMARY KEY,
  FechaVencimientoSoat SMALLDATETIME NOT NULL,
  FechaVencimientoTecnoMecanica SMALLDATETIME NOT NULL

)

DROP TABLE VEHICULO
